# Основные настройки блога
name: "Мой Блог-Портфолио"
description: "Публикую свои проекты, мысли и работы."
baseurl: "" # оставь пустым для GitHub Pages
url: "https://username.github.io" # замени на свой URL

# Пути и плагины
collections:
  posts:
    output: true
    permalink: /:title/

# Разделы сайта
include:
  - _pages
  - _posts

# Markdown настройки
markdown: kramdown
theme: minima

# Соц.сети
social_links:
  email: email@example.com
  github: username

# Структура проекта

📂 my-portfolio/
├── _config.yml
├── _pages/
│   └── about.md
├── _posts/
│   └── 2025-03-20-example-post.md
├── assets/
│   ├── images/
│   │   └── example.jpg
│   └── videos/
│       └── example.mp4
└── index.md

---
layout: default
title: Home
---

<h1>Привет! Это мой блог-портфолио</h1>
<p>Добро пожаловать! Здесь я рассказываю о своих проектах, делюсь мыслями и показываю результаты работы.</p>

<h2>Последние статьи</h2>
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
      <p>{{ post.date | date: "%d %B %Y" }}</p>
    </li>
  {% endfor %}
</ul>

<nav>
  <a href="/">Главная</a> |
  <a href="/about">О себе</a>
</nav>

---
layout: default
title: About Me
---

<h1>О себе</h1>
<p>Привет, я [Твоё Имя]! Здесь я делюсь своими проектами и интересами. Свяжись со мной по почте: [email@example.com]</p>

<nav>
  <a href="/">Главная</a> |
  <a href="/about">О себе</a>
</nav>

---
layout: post
title: "Пример статьи"
date: 2025-03-20
---

<h1>{{ page.title }}</h1>
<p><em>{{ page.date | date: "%d %B %Y"}</em></p>

<p>Это пример статьи. Здесь можно добавлять текст, картинки и видео:</p>

<p>Пример картинки:</p>
<img src="/assets/images/example.jpg" alt="Пример изображения">

<p>Пример видео:</p>
<video controls>
  <source src="/assets/videos/example.mp4" type="video/mp4">
  Ваш браузер не поддерживает видео тег.
</video>

<nav>
  <a href="/">Главная</a> |
  <a href="/about">О себе</a>
</nav>